DROP TABLE IF EXISTS "_Visit" CASCADE;
CREATE TABLE "_Visit" (
  "model" VARCHAR(15) NOT NULL,
  "id" BIGINT NOT NULL,
  "operate" SMALLINT NOT NULL,
  "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

